// Multiple-choice question bank for the /bible-trivia game.
// Derived from the printable trivia pack (app/printables/bible-trivia-pack).
// Distractor rule: for "what is missing/never said" trick questions, every
// distractor must be something clearly present/said, so the trick stays fair.

export type GameQuestion = {
  q: string
  a: string // correct answer
  wrong: [string, string, string]
  ref: string
}

export const EASY: GameQuestion[] = [
  { q: 'What is the very first sentence in the Bible?', a: '"In the beginning God created the heavens and the earth"', wrong: ['"Let there be light"', '"The LORD is my shepherd"', '"In the beginning was the Word"'], ref: 'Genesis 1:1' },
  { q: 'How many days did God take to create the world?', a: 'Six days — then he rested on the seventh', wrong: ['Seven days', 'Three days', 'Forty days'], ref: 'Genesis 1:31–2:2' },
  { q: 'Who were the first man and woman?', a: 'Adam and Eve', wrong: ['Abraham and Sarah', 'Isaac and Rebekah', 'Joseph and Mary'], ref: 'Genesis 2:7, 3:20' },
  { q: 'What was the name of the garden where Adam and Eve lived?', a: 'The Garden of Eden', wrong: ['The Garden of Gethsemane', 'The Garden of Galilee', 'The Garden of Canaan'], ref: 'Genesis 2:8' },
  { q: 'Who built a giant ark to save his family and the animals?', a: 'Noah', wrong: ['Moses', 'Abraham', 'Jonah'], ref: 'Genesis 6:13-14' },
  { q: 'What sign did God put in the sky as a promise never to flood the whole earth again?', a: 'A rainbow', wrong: ['A dove', 'A burning bush', 'A shooting star'], ref: 'Genesis 9:13' },
  { q: 'What baby was hidden in a basket on the Nile River?', a: 'Moses', wrong: ['David', 'Samuel', 'Joseph'], ref: 'Exodus 2:3' },
  { q: 'What sea did God part so the Israelites could walk through on dry ground?', a: 'The Red Sea', wrong: ['The Sea of Galilee', 'The Dead Sea', 'The Jordan River'], ref: 'Exodus 14:21-22' },
  { q: 'How many commandments did God give Moses?', a: 'Ten', wrong: ['Seven', 'Twelve', 'Forty'], ref: 'Exodus 20:1-17' },
  { q: 'What food did God send from heaven to feed the Israelites in the desert?', a: 'Manna', wrong: ['Milk and honey', 'Figs and dates', 'Grapes from Canaan'], ref: 'Exodus 16:14-15' },
  { q: 'Which city’s walls came tumbling down when Israel marched around them and shouted?', a: 'Jericho', wrong: ['Jerusalem', 'Babylon', 'Bethlehem'], ref: 'Joshua 6:20' },
  { q: 'Finish Joshua’s famous words: "As for me and my household..."', a: '"...we will serve the LORD"', wrong: ['"...we will keep the commandments"', '"...we will build a temple"', '"...we will follow Moses"'], ref: 'Joshua 24:15' },
  { q: 'Who was the strongest man in the Bible, whose strength was connected to his long hair?', a: 'Samson', wrong: ['Goliath', 'Saul', 'Gideon'], ref: 'Judges 16:17' },
  { q: 'How many soldiers did God let Gideon keep to fight the huge Midianite army?', a: 'Three hundred', wrong: ['Three thousand', 'Twelve thousand', 'Seventy'], ref: 'Judges 7:7' },
  { q: 'Who was the mother-in-law that Ruth refused to leave?', a: 'Naomi', wrong: ['Orpah', 'Esther', 'Hannah'], ref: 'Ruth 1:14-16' },
  { q: 'What did David use to defeat the giant Goliath?', a: 'A sling and a stone', wrong: ['A sword and shield', 'A spear', 'A bow and arrow'], ref: '1 Samuel 17:49-50' },
  { q: 'Who was Israel’s very first king?', a: 'Saul', wrong: ['David', 'Solomon', 'Samuel'], ref: '1 Samuel 10:24' },
  { q: 'Who was David’s best friend, the king’s own son?', a: 'Jonathan', wrong: ['Absalom', 'Nathan', 'Joab'], ref: '1 Samuel 18:1-3' },
  { q: 'Which king asked God for wisdom instead of money or long life?', a: 'Solomon', wrong: ['David', 'Hezekiah', 'Josiah'], ref: '1 Kings 3:9-12' },
  { q: 'Which prophet was fed by ravens during a long drought?', a: 'Elijah', wrong: ['Elisha', 'Isaiah', 'Jeremiah'], ref: '1 Kings 17:4-6' },
  { q: 'What did the army commander Naaman have to do to be healed of leprosy?', a: 'Wash seven times in the Jordan River', wrong: ['Offer seven sacrifices', 'Pray for seven days', 'Be anointed with oil'], ref: '2 Kings 5:10, 14' },
  { q: 'What did Esther become in the land of Persia?', a: 'The queen', wrong: ['A judge', 'A prophet', 'A shepherdess'], ref: 'Esther 2:17' },
  { q: 'Finish the most famous verse in Psalms: "The LORD is my ___."', a: 'Shepherd', wrong: ['Rock', 'Light', 'King'], ref: 'Psalm 23:1' },
  { q: 'Which tiny insect does Proverbs tell lazy people to watch and learn from?', a: 'The ant', wrong: ['The bee', 'The spider', 'The grasshopper'], ref: 'Proverbs 6:6' },
  { q: 'Those who hope in the LORD will soar on wings like what bird?', a: 'Eagles', wrong: ['Doves', 'Sparrows', 'Ravens'], ref: 'Isaiah 40:31' },
  { q: 'Who was thrown into a den of lions for praying to God?', a: 'Daniel', wrong: ['David', 'Joseph', 'Jeremiah'], ref: 'Daniel 6:16' },
  { q: 'Where were Shadrach, Meshach, and Abednego thrown for refusing to bow to the gold statue?', a: 'Into a blazing furnace', wrong: ['Into a lions’ den', 'Into a deep pit', 'Into a prison cell'], ref: 'Daniel 3:20-21' },
  { q: 'What swallowed Jonah when he ran away from God?', a: 'A huge fish that God provided', wrong: ['A whale', 'A giant squid', 'A sea serpent'], ref: 'Jonah 1:17' },
  { q: 'In what town was Jesus born?', a: 'Bethlehem', wrong: ['Nazareth', 'Jerusalem', 'Capernaum'], ref: 'Matthew 2:1' },
  { q: 'What did the wise men follow to find young Jesus?', a: 'A star', wrong: ['An angel', 'A map', 'A dream'], ref: 'Matthew 2:2, 9' },
  { q: 'What three gifts did the wise men bring?', a: 'Gold, frankincense, and myrrh', wrong: ['Gold, silver, and bronze', 'Bread, wine, and oil', 'Silk, spices, and pearls'], ref: 'Matthew 2:11' },
  { q: 'Where did Mary lay baby Jesus after he was born?', a: 'In a manger', wrong: ['In the inn’s best room', 'In a shepherd’s tent', 'In a basket'], ref: 'Luke 2:7' },
  { q: 'Who did the angels first tell the good news of Jesus’ birth?', a: 'Shepherds watching their flocks at night', wrong: ['The wise men', 'King Herod', 'The priests in the temple'], ref: 'Luke 2:8-11' },
  { q: 'Who baptized Jesus in the Jordan River?', a: 'John the Baptist', wrong: ['Peter', 'Andrew', 'Elijah'], ref: 'Matthew 3:13' },
  { q: 'How many disciples did Jesus choose?', a: 'Twelve', wrong: ['Ten', 'Seven', 'Seventy'], ref: 'Matthew 10:1-2' },
  { q: 'How many loaves and fish did Jesus use to feed more than 5,000 people?', a: 'Five loaves and two fish', wrong: ['Seven loaves and three fish', 'Two loaves and five fish', 'Twelve loaves and twelve fish'], ref: 'Matthew 14:17-21' },
  { q: 'What did Jesus turn water into at a wedding — his very first miracle?', a: 'Wine', wrong: ['Milk', 'Honey', 'Oil'], ref: 'John 2:9-11' },
  { q: 'What short tax collector climbed a sycamore-fig tree to see Jesus?', a: 'Zacchaeus', wrong: ['Matthew', 'Bartimaeus', 'Nicodemus'], ref: 'Luke 19:2-4' },
  { q: 'Finish the most famous verse in the Bible: "For God so loved the world that he gave his one and only ___"', a: 'Son', wrong: ['Word', 'Light', 'Lamb'], ref: 'John 3:16' },
  { q: 'What happened on the third day after Jesus died on the cross?', a: 'He rose from the dead', wrong: ['He ascended into heaven', 'The stone was sealed forever', 'The disciples fled to Galilee'], ref: 'Matthew 28:5-6' },
]

export const MEDIUM: GameQuestion[] = [
  { q: 'What fruit did Adam and Eve eat in the Garden of Eden?', a: 'Trick question — the Bible only says "fruit," never an apple', wrong: ['An apple', 'A fig', 'A pomegranate'], ref: 'Genesis 3:6' },
  { q: 'Who were Adam and Eve’s first two sons?', a: 'Cain and Abel', wrong: ['Jacob and Esau', 'Shem and Ham', 'Isaac and Ishmael'], ref: 'Genesis 4:1-2' },
  { q: 'Whose wife turned into a pillar of salt when she looked back at Sodom?', a: 'Lot’s wife', wrong: ['Noah’s wife', 'Abraham’s wife', 'Job’s wife'], ref: 'Genesis 19:26' },
  { q: 'What did Esau trade his birthright for?', a: 'A meal of bread and lentil stew', wrong: ['A hunting bow', 'Thirty silver coins', 'A field in Canaan'], ref: 'Genesis 25:33-34' },
  { q: 'What new name did God give Jacob after he wrestled with God?', a: 'Israel', wrong: ['Judah', 'Bethel', 'Ephraim'], ref: 'Genesis 32:28' },
  { q: 'What was the first of the ten plagues on Egypt?', a: 'The Nile turned to blood', wrong: ['Frogs everywhere', 'Total darkness', 'Swarms of locusts'], ref: 'Exodus 7:20' },
  { q: 'What did the Israelites put on their doorframes so the final plague would pass over their homes?', a: 'The blood of a lamb', wrong: ['Olive branches', 'A red cord', 'Anointing oil'], ref: 'Exodus 12:7, 13' },
  { q: 'Where exactly did Rahab hide the two Israelite spies?', a: 'On her roof, under stalks of flax', wrong: ['In a dry well', 'Inside the city wall', 'Under grain baskets'], ref: 'Joshua 2:6' },
  { q: 'What amazing thing happened in the sky during the battle at Gibeon?', a: 'The sun stood still and the moon stopped until Israel won', wrong: ['The stars fell like rain', 'It became dark at noon', 'A rainbow circled the sun'], ref: 'Joshua 10:12-13' },
  { q: 'Which woman defeated the mighty general Sisera with a tent peg and a hammer?', a: 'Jael', wrong: ['Deborah', 'Miriam', 'Ruth'], ref: 'Judges 4:21' },
  { q: 'What two-part test did Gideon ask God for using a piece of wool?', a: 'A wet fleece on dry ground, then a dry fleece on wet ground', wrong: ['Fire from a rock, then fire from heaven', 'Thunder at noon, then at midnight', 'A jar of oil that never ran out'], ref: 'Judges 6:36-40' },
  { q: 'Who was Ruth’s sister-in-law who kissed Naomi goodbye and went back to Moab?', a: 'Orpah', wrong: ['Deborah', 'Miriam', 'Abigail'], ref: 'Ruth 1:14' },
  { q: 'What did the priest Eli wrongly think Hannah was doing as she prayed for a son?', a: 'He thought she was drunk — her lips moved but no sound came out', wrong: ['He thought she was asleep', 'He thought she was sick', 'He thought she was singing'], ref: '1 Samuel 1:13-14' },
  { q: 'Where was Saul found when it was time to announce him as king?', a: 'Hiding among the supplies', wrong: ['Praying in the temple', 'Plowing his field', 'Waiting at the city gate'], ref: '1 Samuel 10:22' },
  { q: 'What city was the giant Goliath from?', a: 'Gath', wrong: ['Gaza', 'Ashdod', 'Jericho'], ref: '1 Samuel 17:4' },
  { q: 'When two women both claimed the same baby, what did Solomon order?', a: '"Cut the child in two" — the real mother begged to give the baby away instead', wrong: ['Keep the baby in the palace', 'Cast lots for the baby', 'Have witnesses swear an oath'], ref: '1 Kings 3:24-27' },
  { q: 'Who was the wicked foreign queen who married King Ahab and pushed Baal worship in Israel?', a: 'Jezebel', wrong: ['Vashti', 'Athaliah', 'Delilah'], ref: '1 Kings 16:31' },
  { q: 'What did Elisha ask Elijah for before Elijah was taken up to heaven?', a: 'A double portion of Elijah’s spirit', wrong: ['Elijah’s staff', 'A chariot of fire', 'Half of Elijah’s land'], ref: '2 Kings 2:9' },
  { q: 'Which queen lost her crown for refusing to appear at King Xerxes’ banquet?', a: 'Queen Vashti', wrong: ['Queen Esther', 'Queen Jezebel', 'Queen Bathsheba'], ref: 'Esther 1:10-12, 19' },
  { q: 'Finish Mordecai’s famous challenge: "Who knows but that you have come to your royal position for such a..."', a: '"...time as this?"', wrong: ['"...day as this?"', '"...purpose as this?"', '"...moment as this?"'], ref: 'Esther 4:14' },
  { q: 'How many verses are in Psalm 119, the longest chapter in the whole Bible?', a: '176', wrong: ['150', '119', '200'], ref: 'Psalm 119' },
  { q: 'By which rivers did the exiles sit and weep when they remembered Zion?', a: 'The rivers of Babylon', wrong: ['The rivers of Egypt', 'The rivers of Eden', 'The Jordan River'], ref: 'Psalm 137:1' },
  { q: 'The wife of noble character in Proverbs 31 is worth far more than what?', a: 'Rubies', wrong: ['Gold', 'Pearls', 'Silver'], ref: 'Proverbs 31:10' },
  { q: 'What six-winged heavenly creatures did Isaiah see around God’s throne?', a: 'Seraphim', wrong: ['Cherubim', 'Archangels', 'Watchers'], ref: 'Isaiah 6:2' },
  { q: 'In King Nebuchadnezzar’s dream of a giant statue, what was the head made of?', a: 'Gold', wrong: ['Silver', 'Bronze', 'Iron'], ref: 'Daniel 2:32, 38' },
  { q: 'What words did the mysterious hand write on the palace wall during Belshazzar’s feast?', a: 'Mene, Mene, Tekel, Parsin', wrong: ['Talitha Koum', 'Eli, Eli, Lama Sabachthani', 'Maranatha'], ref: 'Daniel 5:25' },
  { q: 'Was Jonah swallowed by a whale?', a: 'Trick question — the Bible says "a huge fish" and never calls it a whale', wrong: ['Yes, a sperm whale', 'Yes, a blue whale', 'Yes, a killer whale'], ref: 'Jonah 1:17' },
  { q: 'What does the name Immanuel mean?', a: '"God with us"', wrong: ['"God saves"', '"Prince of peace"', '"The anointed one"'], ref: 'Matthew 1:23' },
  { q: 'What is the Golden Rule?', a: '"Do to others what you would have them do to you"', wrong: ['"Love the Lord with all your heart"', '"Do not judge, or you will be judged"', '"Turn the other cheek"'], ref: 'Matthew 7:12' },
  { q: 'Peter asked if he should forgive someone seven times. What did Jesus say?', a: 'Not seven times, but seventy-seven times', wrong: ['Yes, seven times is enough', 'Three times, then walk away', 'Only if they apologize first'], ref: 'Matthew 18:21-22' },
  { q: 'What job did the prodigal son end up doing in the far country when his money ran out?', a: 'Feeding pigs', wrong: ['Shepherding sheep', 'Picking grapes', 'Begging at the temple'], ref: 'Luke 15:15' },
  { q: 'How did four friends get their paralyzed friend to Jesus in a packed house?', a: 'They dug through the roof and lowered him down on his mat', wrong: ['They climbed through a window', 'They carried him past the guards', 'They waited three days at the door'], ref: 'Mark 2:4' },
  { q: 'What did the poor widow put in the temple offering?', a: 'Two very small copper coins — everything she had', wrong: ['One silver shekel', 'A gold ring', 'A basket of grain'], ref: 'Mark 12:42-44' },
  { q: 'What did Jesus tell Nicodemus a person must be to see the kingdom of God?', a: 'Born again', wrong: ['Baptized by John', 'Perfect in the law', 'Rich in good deeds'], ref: 'John 3:3' },
  { q: 'In which city were believers first called Christians?', a: 'Antioch', wrong: ['Jerusalem', 'Rome', 'Ephesus'], ref: 'Acts 11:26' },
]

export const HARD: GameQuestion[] = [
  { q: 'Who is the oldest person recorded in the Bible, and how long did he live?', a: 'Methuselah — 969 years', wrong: ['Noah — 950 years', 'Adam — 930 years', 'Abraham — 175 years'], ref: 'Genesis 5:27' },
  { q: 'How many of every clean animal did Noah take aboard the ark?', a: 'Seven pairs — not just two', wrong: ['Just two of every animal', 'Three pairs', 'Twelve of each'], ref: 'Genesis 7:2' },
  { q: 'What mysterious priest-king brought out bread and wine and blessed Abram?', a: 'Melchizedek, king of Salem', wrong: ['Aaron the high priest', 'Jethro, priest of Midian', 'Eli the priest'], ref: 'Genesis 14:18' },
  { q: 'Which two Hebrew midwives bravely disobeyed Pharaoh’s order to kill baby boys?', a: 'Shiphrah and Puah', wrong: ['Miriam and Jochebed', 'Ruth and Naomi', 'Huldah and Deborah'], ref: 'Exodus 1:15-17' },
  { q: 'What was Joshua’s original name before Moses renamed him?', a: 'Hoshea', wrong: ['Nun', 'Elishua', 'Shammua'], ref: 'Numbers 13:16' },
  { q: 'What password did the men of Gilead use at the Jordan River because their enemies couldn’t pronounce it?', a: '"Shibboleth"', wrong: ['"Sibboleth"', '"Hallelujah"', '"Hosanna"'], ref: 'Judges 12:5-6' },
  { q: 'What did Samuel name the memorial stone after God routed the Philistines?', a: 'Ebenezer — "Thus far the LORD has helped us"', wrong: ['Bethel — "House of God"', 'Gilgal — "Rolled away"', 'Mizpah — "Watchtower"'], ref: '1 Samuel 7:12' },
  { q: 'How many people in Israel did God say had never bowed to Baal, when Elijah thought he was the only one left?', a: 'Seven thousand', wrong: ['Three hundred', 'Twelve thousand', 'A hundred and forty-four thousand'], ref: '1 Kings 19:18' },
  { q: 'How many Assyrian soldiers did the angel of the LORD strike down in one night?', a: 'A hundred and eighty-five thousand', wrong: ['A hundred thousand', 'Seventy thousand', 'Forty thousand'], ref: '2 Kings 19:35' },
  { q: 'What is famously missing from the entire book of Esther?', a: 'Any mention of God’s name', wrong: ['Any feasts or banquets', 'Any battles', 'Any kings'], ref: 'Esther' },
  { q: 'What mysterious Hebrew word appears 71 times in Psalms and probably signals a musical pause?', a: 'Selah', wrong: ['Amen', 'Maranatha', 'Hosanna'], ref: 'e.g. Psalm 3:2' },
  { q: 'Which psalm did Jesus quote from the cross — "My God, my God, why have you forsaken me?"', a: 'Psalm 22', wrong: ['Psalm 23', 'Psalm 51', 'Psalm 91'], ref: 'Psalm 22:1; Matthew 27:46' },
  { q: 'A long stretch of Daniel isn’t written in Hebrew. What language is Daniel 2:4–7:28 written in?', a: 'Aramaic', wrong: ['Greek', 'Persian', 'Egyptian'], ref: 'Daniel 2:4' },
  { q: 'What was the name of Jonah’s father?', a: 'Amittai', wrong: ['Elkanah', 'Zebedee', 'Abinadab'], ref: 'Jonah 1:1' },
  { q: 'How many wise men does the Bible say visited Jesus?', a: 'Trick question — Matthew never gives a number', wrong: ['Three', 'Twelve', 'Two'], ref: 'Matthew 2:1, 11' },
  { q: 'Who appeared with Jesus at the transfiguration?', a: 'Moses and Elijah', wrong: ['Abraham and Isaac', 'David and Solomon', 'Enoch and Elijah'], ref: 'Matthew 17:3' },
  { q: 'Where did Jesus tell Peter to find a coin to pay the temple tax?', a: 'In the mouth of the first fish he caught', wrong: ['Under a stone by the road', 'In the money bag Judas kept', 'From the widow’s offering'], ref: 'Matthew 17:27' },
  { q: 'What word does Mark use more than 40 times to keep his fast-paced Gospel racing along?', a: '"Immediately"', wrong: ['"Behold"', '"Truly"', '"Repent"'], ref: 'Gospel of Mark' },
  { q: 'What was the name of the servant whose ear Peter cut off — a detail only John records?', a: 'Malchus', wrong: ['Alexander', 'Rufus', 'Barabbas'], ref: 'John 18:10' },
  { q: 'In what three languages was the sign over the cross written?', a: 'Aramaic, Latin, and Greek', wrong: ['Hebrew, Greek, and Egyptian', 'Latin, Greek, and Persian', 'Aramaic, Hebrew, and Latin'], ref: 'John 19:20' },
  { q: 'Exactly how many fish were in the net when the risen Jesus met the disciples at the shore?', a: '153', wrong: ['120', '77', '40'], ref: 'John 21:11' },
  { q: 'When did God change Saul’s name to Paul?', a: 'Trick question — he never did. Saul "was also called Paul" all along', wrong: ['On the road to Damascus', 'At his baptism', 'When he first met Peter'], ref: 'Acts 13:9' },
  { q: 'Who fell asleep and dropped from a third-story window during Paul’s long sermon?', a: 'Eutychus — and Paul raised him alive', wrong: ['Timothy', 'Silas', 'John Mark'], ref: 'Acts 20:9-10' },
  { q: 'Paul spoke the letter to the Romans aloud — who actually wrote it down, and even adds his own hello?', a: 'Tertius', wrong: ['Silas', 'Luke', 'Onesimus'], ref: 'Romans 16:22' },
  { q: 'Why is there no temple in the new Jerusalem?', a: 'Because the Lord God Almighty and the Lamb are its temple', wrong: ['Because it was destroyed in the last battle', 'Because every house is a temple', 'Because the ark of the covenant replaced it'], ref: 'Revelation 21:22' },
]

export const ALL_QUESTIONS: GameQuestion[] = [...EASY, ...MEDIUM, ...HARD]
